2025-05-06 11:13:04,612 INFO    MainThread:1702817 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-05-06 11:13:04,612 INFO    MainThread:1702817 [wandb_setup.py:_flush():67] Configure stats pid to 1702817
2025-05-06 11:13:04,612 INFO    MainThread:1702817 [wandb_setup.py:_flush():67] Loading settings from /home/mwahlin/.config/wandb/settings
2025-05-06 11:13:04,612 INFO    MainThread:1702817 [wandb_setup.py:_flush():67] Loading settings from /usr/terminus/data-xrm-01/stamplab/users/mwahlin/2025/trab_master/supertrab/wandb/settings
2025-05-06 11:13:04,612 INFO    MainThread:1702817 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-05-06 11:13:04,612 INFO    MainThread:1702817 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /usr/terminus/data-xrm-01/stamplab/users/mwahlin/2025/trab_master/supertrab/wandb/run-20250506_111304-g4qqtq28/logs/debug.log
2025-05-06 11:13:04,612 INFO    MainThread:1702817 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /usr/terminus/data-xrm-01/stamplab/users/mwahlin/2025/trab_master/supertrab/wandb/run-20250506_111304-g4qqtq28/logs/debug-internal.log
2025-05-06 11:13:04,612 INFO    MainThread:1702817 [wandb_init.py:init():761] calling init triggers
2025-05-06 11:13:04,612 INFO    MainThread:1702817 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'_wandb': {}}
2025-05-06 11:13:04,612 INFO    MainThread:1702817 [wandb_init.py:init():784] starting backend
2025-05-06 11:13:04,613 INFO    MainThread:1702817 [wandb_init.py:init():788] sending inform_init request
2025-05-06 11:13:04,624 INFO    MainThread:1702817 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-05-06 11:13:04,625 INFO    MainThread:1702817 [wandb_init.py:init():803] backend started and connected
2025-05-06 11:13:04,629 INFO    MainThread:1702817 [wandb_init.py:init():896] updated telemetry
2025-05-06 11:13:04,656 INFO    MainThread:1702817 [wandb_init.py:init():920] communicating run to backend with 90.0 second timeout
2025-05-06 11:13:05,018 INFO    MainThread:1702817 [wandb_init.py:init():995] starting run threads in backend
2025-05-06 11:13:05,700 INFO    MainThread:1702817 [wandb_run.py:_console_start():2377] atexit reg
2025-05-06 11:13:05,700 INFO    MainThread:1702817 [wandb_run.py:_redirect():2227] redirect: wrap_raw
2025-05-06 11:13:05,700 INFO    MainThread:1702817 [wandb_run.py:_redirect():2292] Wrapping output streams.
2025-05-06 11:13:05,701 INFO    MainThread:1702817 [wandb_run.py:_redirect():2317] Redirects installed.
2025-05-06 11:13:05,706 INFO    MainThread:1702817 [wandb_init.py:init():1037] run started, returning control to user process
2025-05-06 11:13:05,707 INFO    MainThread:1702817 [wandb_run.py:_config_callback():1261] config_cb None None {'image_size': 128, 'train_batch_size': 8, 'eval_batch_size': 8, 'num_epochs': 50, 'gradient_accumulation_steps': 1, 'learning_rate': 0.0001, 'lr_warmup_steps': 500, 'save_image_epochs': 10, 'ds_factor': 4, 'mixed_precision': 'fp16', 'output_dir': 'samples/supertrab-diffusion-sr-2d-v4', 'seed': 0, 'cfg_dropout_prob': 0.1}
2025-05-06 11:25:59,190 WARNING MsgRouterThr:1702817 [router.py:message_loop():77] message_loop has been closed
Traceback (most recent call last):
  File "/usr/terminus/data-xrm-01/stamplab/users/mwahlin/mamba/envs/ML_env/lib/python3.10/site-packages/wandb/sdk/interface/router_sock.py", line 28, in _read_message
    resp = self._sock_client.read_server_response(timeout=1)
  File "/usr/terminus/data-xrm-01/stamplab/users/mwahlin/mamba/envs/ML_env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 285, in read_server_response
    data = self._read_packet_bytes(timeout=timeout)
  File "/usr/terminus/data-xrm-01/stamplab/users/mwahlin/mamba/envs/ML_env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 270, in _read_packet_bytes
    raise SockClientClosedError
wandb.sdk.lib.sock_client.SockClientClosedError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/terminus/data-xrm-01/stamplab/users/mwahlin/mamba/envs/ML_env/lib/python3.10/site-packages/wandb/sdk/interface/router.py", line 70, in message_loop
    msg = self._read_message()
  File "/usr/terminus/data-xrm-01/stamplab/users/mwahlin/mamba/envs/ML_env/lib/python3.10/site-packages/wandb/sdk/interface/router_sock.py", line 30, in _read_message
    raise MessageRouterClosedError from e
wandb.sdk.interface.router.MessageRouterClosedError
2025-05-06 11:25:59,195 INFO    MsgRouterThr:1702817 [mailbox.py:close():115] Closing mailbox, abandoning 2 handles.
