2025-04-23 18:01:54,749 INFO    MainThread:771132 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-04-23 18:01:54,749 INFO    MainThread:771132 [wandb_setup.py:_flush():67] Configure stats pid to 771132
2025-04-23 18:01:54,749 INFO    MainThread:771132 [wandb_setup.py:_flush():67] Loading settings from /home/mwahlin/.config/wandb/settings
2025-04-23 18:01:54,749 INFO    MainThread:771132 [wandb_setup.py:_flush():67] Loading settings from /usr/terminus/data-xrm-01/stamplab/users/mwahlin/2025/trab_master/supertrab/wandb/settings
2025-04-23 18:01:54,749 INFO    MainThread:771132 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-04-23 18:01:54,749 INFO    MainThread:771132 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /usr/terminus/data-xrm-01/stamplab/users/mwahlin/2025/trab_master/supertrab/wandb/run-20250423_180154-m700pkmp/logs/debug.log
2025-04-23 18:01:54,749 INFO    MainThread:771132 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /usr/terminus/data-xrm-01/stamplab/users/mwahlin/2025/trab_master/supertrab/wandb/run-20250423_180154-m700pkmp/logs/debug-internal.log
2025-04-23 18:01:54,749 INFO    MainThread:771132 [wandb_init.py:init():761] calling init triggers
2025-04-23 18:01:54,749 INFO    MainThread:771132 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'_wandb': {}}
2025-04-23 18:01:54,750 INFO    MainThread:771132 [wandb_init.py:init():784] starting backend
2025-04-23 18:01:54,750 INFO    MainThread:771132 [wandb_init.py:init():788] sending inform_init request
2025-04-23 18:01:54,759 INFO    MainThread:771132 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-04-23 18:01:54,760 INFO    MainThread:771132 [wandb_init.py:init():803] backend started and connected
2025-04-23 18:01:54,761 INFO    MainThread:771132 [wandb_init.py:init():896] updated telemetry
2025-04-23 18:01:54,774 INFO    MainThread:771132 [wandb_init.py:init():920] communicating run to backend with 90.0 second timeout
2025-04-23 18:01:55,124 INFO    MainThread:771132 [wandb_init.py:init():995] starting run threads in backend
2025-04-23 18:01:55,394 INFO    MainThread:771132 [wandb_run.py:_console_start():2377] atexit reg
2025-04-23 18:01:55,394 INFO    MainThread:771132 [wandb_run.py:_redirect():2227] redirect: wrap_raw
2025-04-23 18:01:55,394 INFO    MainThread:771132 [wandb_run.py:_redirect():2292] Wrapping output streams.
2025-04-23 18:01:55,394 INFO    MainThread:771132 [wandb_run.py:_redirect():2317] Redirects installed.
2025-04-23 18:01:55,398 INFO    MainThread:771132 [wandb_init.py:init():1037] run started, returning control to user process
2025-04-23 18:02:20,236 WARNING MsgRouterThr:771132 [router.py:message_loop():77] message_loop has been closed
Traceback (most recent call last):
  File "/usr/terminus/data-xrm-01/stamplab/users/mwahlin/mamba/envs/ML_env/lib/python3.10/site-packages/wandb/sdk/interface/router_sock.py", line 28, in _read_message
    resp = self._sock_client.read_server_response(timeout=1)
  File "/usr/terminus/data-xrm-01/stamplab/users/mwahlin/mamba/envs/ML_env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 285, in read_server_response
    data = self._read_packet_bytes(timeout=timeout)
  File "/usr/terminus/data-xrm-01/stamplab/users/mwahlin/mamba/envs/ML_env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 270, in _read_packet_bytes
    raise SockClientClosedError
wandb.sdk.lib.sock_client.SockClientClosedError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/terminus/data-xrm-01/stamplab/users/mwahlin/mamba/envs/ML_env/lib/python3.10/site-packages/wandb/sdk/interface/router.py", line 70, in message_loop
    msg = self._read_message()
  File "/usr/terminus/data-xrm-01/stamplab/users/mwahlin/mamba/envs/ML_env/lib/python3.10/site-packages/wandb/sdk/interface/router_sock.py", line 30, in _read_message
    raise MessageRouterClosedError from e
wandb.sdk.interface.router.MessageRouterClosedError
2025-04-23 18:02:20,241 INFO    MsgRouterThr:771132 [mailbox.py:close():115] Closing mailbox, abandoning 1 handles.
